language: php

php:
  - nightly
  - 7
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  
before_script:
  - pip install --user codecov
  - mkdir -p ~/tmp
  - cd /home/travis/build/mkungla/libhowi-filesystem/tests
script:
  - phpunit
  
after_success:
  - codecov