language: php

php:
  - 7
  - 5.6
  - 5.5
  
before_script:
  - pip install --user codecov
  - mkdir -p ~/tmp
  - cd /home/travis/build/mkungla/libhowi-filesystem/tests
script:
  - phpunit
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover